site_name: Dom's Docs
site_url: https://docs.dominicgerman.com
repo_url: https://github.com/dominicgerman/dominicgerman.github.io
repo_name: dominicgerman/homelab-wiki

theme:
  name: material
  language: en
  favicon: assets/favicon.png
  features:
    - content.code.copy
    - navigation.footer
    - navigation.path
    - navigation.tabs
    - navigation.sections
    - toc.integrate
  font:
    text: Roboto
    code: JetBrains Mono
  icon:
    logo: fontawesome/solid/server
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: deep purple
      accent: deep orange

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: deep purple
      accent: deep orange
markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.details # enables collapsible admonitions
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true

extra:
  social:
    - icon: simple/curl
      link: https://dominicgerman.com
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/dominic-german
nav:
  - Setup:
      - "setup/index.md"
      - How To Set Up a Media Server: "setup/mediaserver.md"
      - Create a Reusable Boot Drive with Ventoy: "setup/ventoy.md"
  - Services:
      - Jellyfin: "services/jellyfin.md"
      - Nextcloud: "services/nextcloud.md"
  - Topics:
      - Mergerfs: "topics/mergerfs.md"
  - Reference:
      - Network diagram: "reference/network-diagram.md"
